// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYa7kURYjWN1mm34V_ukcJ7nZW0-9QCqw',
    appId: '1:808921712419:web:e60e3356e73b0bcd632e96',
    messagingSenderId: '808921712419',
    projectId: 'ebook-app-b7a78',
    authDomain: 'ebook-app-b7a78.firebaseapp.com',
    storageBucket: 'ebook-app-b7a78.appspot.com',
    measurementId: 'G-L45JGFFV3M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHIKmU1C6JH78w4HaZ-CvLmPFc0RURsTs',
    appId: '1:808921712419:android:ddb643283e31aae0632e96',
    messagingSenderId: '808921712419',
    projectId: 'ebook-app-b7a78',
    storageBucket: 'ebook-app-b7a78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4PGAaGsjWhD4KyHtlA6qa48h3qYXoxT8',
    appId: '1:808921712419:ios:6c62ce5f70890293632e96',
    messagingSenderId: '808921712419',
    projectId: 'ebook-app-b7a78',
    storageBucket: 'ebook-app-b7a78.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4PGAaGsjWhD4KyHtlA6qa48h3qYXoxT8',
    appId: '1:808921712419:ios:6c62ce5f70890293632e96',
    messagingSenderId: '808921712419',
    projectId: 'ebook-app-b7a78',
    storageBucket: 'ebook-app-b7a78.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
